# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogame',
            name='developers',
        ),
        migrations.AddField(
            model_name='videogame',
            name='developers',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='videogames.Developer'),
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='genres',
        ),
        migrations.AddField(
            model_name='videogame',
            name='genres',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='videogames.Genre'),
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='platforms',
        ),
        migrations.AddField(
            model_name='videogame',
            name='platforms',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='videogames.Platform'),
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='publishers',
        ),
        migrations.AddField(
            model_name='videogame',
            name='publishers',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='videogames.Publisher'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='rating',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='videogames.Rating'),
        ),
    ]
