# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0003_auto_20160320_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='platforms',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='videogames.Platform'),
        ),
    ]
