# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0004_videogame_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='developers',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='videogames.Developer'),
        ),
        migrations.AddField(
            model_name='videogame',
            name='publishers',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='videogames.Publisher'),
        ),
        migrations.AddField(
            model_name='videogame',
            name='rating',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='videogames.Rating'),
        ),
    ]
