# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developers', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='-unknown-', max_length=100)),
                ('description', models.CharField(default='No description', max_length=1000)),
                ('brief', models.CharField(default='No brief', max_length=200)),
                ('release_date', models.DateTimeField()),
                ('developers', models.ManyToManyField(to='videogames.Developers')),
                ('genres', models.ManyToManyField(to='videogames.Genres')),
                ('platforms', models.ManyToManyField(to='videogames.Platforms')),
                ('publishers', models.ManyToManyField(to='videogames.Publishers')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videogames.Ratings')),
            ],
            options={
                'ordering': ('release_date',),
            },
        ),
    ]
