# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age_Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_rating', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Max_Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_players', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='videogame',
            options={'ordering': ('title',)},
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='release_date',
        ),
        migrations.AddField(
            model_name='videogame',
            name='has_multiplayer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videogame',
            name='age_rating',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='videogames.Age_Rating'),
        ),
        migrations.AddField(
            model_name='videogame',
            name='max_players',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='videogames.Max_Players'),
        ),
    ]
