# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0002_auto_20160331_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogame',
            name='platform',
        ),
        migrations.AddField(
            model_name='videogame',
            name='platform',
            field=models.ForeignKey(default='3DS', on_delete=django.db.models.deletion.CASCADE, to='videogames.Platform'),
            preserve_default=False,
        ),
    ]
