# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0003_remove_videogame_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='game',
            field=models.ForeignKey(default='Cubic Ninja', on_delete=django.db.models.deletion.CASCADE, related_name='games', to='videogames.VideoGame'),
            preserve_default=False,
        ),
    ]
