# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0003_auto_20160316_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='developers',
            new_name='developer',
        ),
    ]
