# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0004_review_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogame',
            name='rating',
        ),
    ]
