# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0004_auto_20160321_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='age_rating',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='videogames.Age_Rating'),
        ),
    ]
