# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0006_auto_20160331_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='games',
        ),
        migrations.AddField(
            model_name='videogame',
            name='genre',
            field=models.ManyToManyField(to='videogames.Genre'),
        ),
    ]
