# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0007_auto_20160331_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videogame',
            options={},
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='platform',
        ),
        migrations.AddField(
            model_name='videogame',
            name='platform',
            field=models.ManyToManyField(to='videogames.Platform'),
        ),
    ]
