# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0007_remove_videogame_age_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Age_Rating',
            new_name='AgeRating',
        ),
        migrations.RenameModel(
            old_name='Max_Players',
            new_name='MaxPlayers',
        ),
        migrations.RenameField(
            model_name='agerating',
            old_name='age_rating',
            new_name='ageRating',
        ),
        migrations.RenameField(
            model_name='maxplayers',
            old_name='max_players',
            new_name='maxPlayers',
        ),
        migrations.RenameField(
            model_name='videogame',
            old_name='has_multiplayer',
            new_name='hasMultiplayer',
        ),
        migrations.RenameField(
            model_name='videogame',
            old_name='max_players',
            new_name='maxPlayers',
        ),
        migrations.AddField(
            model_name='videogame',
            name='ageRating',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='videogames.AgeRating'),
        ),
    ]
