# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0008_auto_20160331_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videogames.VideoGame')),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='game',
        ),
        migrations.AddField(
            model_name='gamereview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videogames.Review'),
        ),
        migrations.AddField(
            model_name='videogame',
            name='reviews',
            field=models.ManyToManyField(through='videogames.GameReview', to='videogames.Review'),
        ),
    ]
