# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0008_auto_20160321_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='rating',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='videogames.Rating'),
        ),
    ]
