# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0009_auto_20160331_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamereview',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamereview',
            name='review',
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='reviews',
        ),
        migrations.AddField(
            model_name='review',
            name='videogame',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='videogame_review', to='videogames.VideoGame'),
        ),
        migrations.DeleteModel(
            name='GameReview',
        ),
    ]
