# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 13:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videogames', '0010_auto_20160322_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('header', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=300)),
                ('game', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='videogame', to='videogames.VideoGame')),
                ('rating', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='videogames.Rating')),
                ('username', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
