# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0011_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='header',
        ),
        migrations.AddField(
            model_name='review',
            name='heading',
            field=models.CharField(default=' ', max_length=40),
            preserve_default=False,
        ),
    ]
