# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0012_auto_20160323_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='review',
            name='heading',
            field=models.CharField(default=' ', max_length=40),
        ),
    ]
