# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0014_auto_20160323_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='headquarters',
            field=models.CharField(default='def', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developer',
            name='market',
            field=models.IntegerField(choices=[(1, 'Worldwide'), (2, 'Regional'), (3, 'Country')], default=1),
        ),
        migrations.AddField(
            model_name='platform',
            name='consoleType',
            field=models.IntegerField(choices=[(1, 'Console'), (2, 'Handheld'), (3, 'Mobile'), (4, 'PC')], default=1),
        ),
        migrations.AddField(
            model_name='platform',
            name='manufactorer',
            field=models.CharField(default='def', max_length=50),
            preserve_default=False,
        ),
    ]
