# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0015_auto_20160324_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='headquarters',
            field=models.CharField(default='def', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='market',
            field=models.IntegerField(choices=[(1, 'Worldwide'), (2, 'Regional'), (3, 'Country')], default=1),
        ),
    ]
