# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0016_auto_20160324_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='manufactorer',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
